name = "image-resize-cache"
main = "src/index.ts"
compatibility_date = "2022-11-18"
usage_model = "bundled"

r2_buckets = [
    { binding = "CACHE_BUCKET", bucket_name = "ml-images-cache", preview_bucket_name = "ml-images-cache"}
]